"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {AlertTriangle,CalendarClock,CheckCircle2,FileText,Loader2,Users} from "lucide-react";
import {createClient} from "@/lib/supabase/client";
export default function LiveDashboard(){
 const s=useMemo(()=>createClient(),[]),[c,setC]=useState({groups:0,contents:0,queue:0,posting:0,posted:0,failed:0}),[error,setError]=useState(""),[updated,setUpdated]=useState<Date|null>(null);
 const load=useCallback(async()=>{const start=new Date();start.setHours(0,0,0,0);const end=new Date(start);end.setDate(end.getDate()+1);const now=new Date().toISOString();const r=await Promise.all([
 s.from("groups").select("id",{count:"exact",head:true}),s.from("content_items").select("id",{count:"exact",head:true}),s.from("queue_items").select("id",{count:"exact",head:true}).in("status",["pending","posting"]).gte("scheduled_at",now).lt("scheduled_at",end.toISOString()),s.from("queue_items").select("id",{count:"exact",head:true}).eq("status","posting"),s.from("posting_logs").select("id",{count:"exact",head:true}).eq("result","posted").gte("posted_at",start.toISOString()).lt("posted_at",end.toISOString()),s.from("posting_logs").select("id",{count:"exact",head:true}).eq("result","failed").gte("posted_at",start.toISOString()).lt("posted_at",end.toISOString())]);setError(r.map(x=>x.error).find(Boolean)?.message??"");setC({groups:r[0].count??0,contents:r[1].count??0,queue:r[2].count??0,posting:r[3].count??0,posted:r[4].count??0,failed:r[5].count??0});setUpdated(new Date())},[s]);
 useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),15000);const ch=s.channel("v13-dashboard-live").on("postgres_changes",{event:"*",schema:"public",table:"queue_items"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"posting_logs"},()=>void load()).subscribe();return()=>{clearInterval(timer);void s.removeChannel(ch)}},[load,s]);
 const cards=[["กลุ่มทั้งหมด",c.groups,Users],["คอนเทนต์",c.contents,FileText],["คิวที่เหลือวันนี้",c.queue,CalendarClock],["กำลังโพสต์",c.posting,Loader2],["สำเร็จวันนี้",c.posted,CheckCircle2],["ล้มเหลววันนี้",c.failed,AlertTriangle]] as const;
 return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-2"><div><h2 className="text-xl font-black text-slate-900">สถานะระบบแบบอัตโนมัติ</h2><p className="text-sm text-slate-500">อัปเดตเมื่อ Queue/History เปลี่ยน และรีเฟรชสำรองทุก 15 วินาที</p></div><span className="text-xs text-slate-400">ล่าสุด {updated?updated.toLocaleTimeString("th-TH"):"-"}</span></div>{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([label,value,Icon])=><div className="card" key={label}><Icon className="text-indigo-600"/><p className="mt-5 text-4xl font-black text-slate-900">{value}</p><p className="mt-1 text-sm text-slate-500">{label}</p></div>)}</div></div>;
}
