"use client";
import { useEffect, useMemo, useState } from "react";
import { createBrowserClient } from "@supabase/ssr";
import { Copy, Pencil, Plus, Search, Trash2, X } from "lucide-react";

type Item={id:string;title:string;body:string;category:string|null;hashtags:string|null;status:"draft"|"ready"|"archived";created_at:string};
type Form={title:string;body:string;category:string;hashtags:string;status:"draft"|"ready"|"archived"};
const blank:Form={title:"",body:"",category:"",hashtags:"",status:"ready"};
export default function ContentLibrary(){
 const supabase=createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!);
 const [items,setItems]=useState<Item[]>([]),[q,setQ]=useState(""),[open,setOpen]=useState(false),[editing,setEditing]=useState<string|null>(null),[form,setForm]=useState(blank),[busy,setBusy]=useState(false);
 async function load(){const {data}=await supabase.from("content_items").select("*").order("created_at",{ascending:false});setItems((data||[]) as Item[])}
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>items.filter(i=>(i.title+" "+i.body+" "+(i.category||"")).toLowerCase().includes(q.toLowerCase())),[items,q]);
 function start(item?:Item){if(item){setEditing(item.id);setForm({title:item.title,body:item.body,category:item.category||"",hashtags:item.hashtags||"",status:item.status})}else{setEditing(null);setForm(blank)}setOpen(true)}
 async function save(){if(!form.title.trim()||!form.body.trim())return alert("กรอกชื่อและข้อความก่อนค่ะ");setBusy(true);const payload={...form,updated_at:new Date().toISOString()};const res=editing?await supabase.from("content_items").update(payload).eq("id",editing):await supabase.from("content_items").insert(payload);setBusy(false);if(res.error)return alert(res.error.message);setOpen(false);load()}
 async function remove(id:string){if(!confirm("ลบคอนเทนต์นี้หรือไม่?"))return;const {error}=await supabase.from("content_items").delete().eq("id",id);if(error)alert(error.message);else load()}
 async function duplicate(i:Item){const {error}=await supabase.from("content_items").insert({title:i.title+" (สำเนา)",body:i.body,category:i.category,hashtags:i.hashtags,status:"draft"});if(error)alert(error.message);else load()}
 return <div className="space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:justify-between"><div className="relative max-w-md flex-1"><Search className="absolute left-3 top-3 text-white/40" size={18}/><input className="input pl-10" placeholder="ค้นหาคอนเทนต์..." value={q} onChange={e=>setQ(e.target.value)}/></div><button className="btn-primary" onClick={()=>start()}><Plus size={18}/>เพิ่มคอนเทนต์</button></div>
 <div className="grid gap-4 xl:grid-cols-2">{filtered.map(i=><article key={i.id} className="card"><div className="flex items-start justify-between gap-3"><div><span className="badge">{i.category||"ทั่วไป"}</span><h3 className="mt-3 text-lg font-bold">{i.title}</h3></div><span className="text-xs text-white/45">{i.status}</span></div><p className="mt-3 line-clamp-4 whitespace-pre-wrap text-sm text-white/65">{i.body}</p>{i.hashtags&&<p className="mt-3 text-sm text-cyan-300">{i.hashtags}</p>}<div className="mt-5 flex gap-2"><button className="btn-ghost" onClick={()=>start(i)}><Pencil size={16}/>แก้ไข</button><button className="btn-ghost" onClick={()=>duplicate(i)}><Copy size={16}/>ทำสำเนา</button><button className="btn-danger" onClick={()=>remove(i.id)}><Trash2 size={16}/></button></div></article>)}</div>{filtered.length===0&&<div className="empty">ยังไม่มีคอนเทนต์ กด “เพิ่มคอนเทนต์” เพื่อเริ่มใช้งาน</div>}
 {open&&<div className="modal"><div className="modal-card"><div className="flex justify-between"><h2 className="text-xl font-bold">{editing?"แก้ไขคอนเทนต์":"เพิ่มคอนเทนต์"}</h2><button onClick={()=>setOpen(false)}><X/></button></div><div className="mt-5 grid gap-4"><label>ชื่อ<input className="input mt-1" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>หมวดหมู่<input className="input mt-1" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>ข้อความ<textarea className="input mt-1 min-h-40" value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/></label><label>Hashtag<input className="input mt-1" placeholder="#ขายของ #รีวิว" value={form.hashtags} onChange={e=>setForm({...form,hashtags:e.target.value})}/></label><label>สถานะ<select className="input mt-1" value={form.status} onChange={e=>setForm({...form,status:e.target.value as any})}><option value="draft">Draft</option><option value="ready">Ready</option><option value="archived">Archived</option></select></label><button className="btn-primary justify-center" disabled={busy} onClick={save}>{busy?"กำลังบันทึก...":"บันทึก"}</button></div></div></div>}</div>
}
