"use client";
import {useEffect,useState} from "react";import {createBrowserClient} from "@supabase/ssr";import {CheckCircle2,Plus,Trash2} from "lucide-react";
type Group={id:string;name:string};type Content={id:string;title:string};type Q={id:string;scheduled_at:string;status:string;groups:{name:string}|null;content_items:{title:string}|null};
export default function DailyQueue(){const s=createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!);const [groups,setGroups]=useState<Group[]>([]),[contents,setContents]=useState<Content[]>([]),[rows,setRows]=useState<Q[]>([]),[group,setGroup]=useState(""),[content,setContent]=useState(""),[when,setWhen]=useState("");
async function load(){const [{data:g},{data:c},{data:q}]=await Promise.all([s.from("groups").select("id,name").eq("active",true).order("name"),s.from("content_items").select("id,title").eq("status","ready").order("created_at",{ascending:false}),s.from("queue_items").select("id,scheduled_at,status,groups(name),content_items(title)").order("scheduled_at")]);setGroups((g||[]) as Group[]);setContents((c||[]) as Content[]);setRows((q||[]) as unknown as Q[])}useEffect(()=>{load()},[]);
async function add(){if(!group||!content||!when)return alert("เลือกกลุ่ม คอนเทนต์ และเวลาให้ครบค่ะ");const {error}=await s.from("queue_items").insert({group_id:group,content_id:content,scheduled_at:new Date(when).toISOString()});if(error)alert(error.message);else{setWhen("");load()}}
async function status(r:Q,value:string){const {error}=await s.from("queue_items").update({status:value,updated_at:new Date().toISOString()}).eq("id",r.id);if(error)return alert(error.message);if(value==="posted")await s.from("posting_logs").insert({queue_id:r.id,result:"posted"});load()}
async function del(id:string){if(confirm("ลบรายการนี้หรือไม่?")){await s.from("queue_items").delete().eq("id",id);load()}}
return <div className="space-y-6"><div className="card grid gap-3 lg:grid-cols-[1fr_1fr_1fr_auto]"><select className="input" value={group} onChange={e=>setGroup(e.target.value)}><option value="">เลือก Facebook Group</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><select className="input" value={content} onChange={e=>setContent(e.target.value)}><option value="">เลือกคอนเทนต์</option>{contents.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select><input className="input" type="datetime-local" value={when} onChange={e=>setWhen(e.target.value)}/><button className="btn-primary" onClick={add}><Plus size={18}/>เข้าคิว</button></div><div className="overflow-hidden rounded-2xl border border-white/10"><table className="w-full text-left text-sm"><thead className="bg-white/5 text-white/50"><tr><th className="p-4">เวลา</th><th>กลุ่ม</th><th>คอนเทนต์</th><th>สถานะ</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t border-white/10"><td className="p-4">{new Date(r.scheduled_at).toLocaleString("th-TH")}</td><td>{r.groups?.name||"-"}</td><td>{r.content_items?.title||"-"}</td><td><select className="rounded-lg bg-white/10 p-2" value={r.status} onChange={e=>status(r,e.target.value)}><option value="pending">Pending</option><option value="posted">Posted</option><option value="failed">Failed</option><option value="skipped">Skipped</option></select></td><td><button className="btn-danger" onClick={()=>del(r.id)}><Trash2 size={16}/></button></td></tr>)}</tbody></table>{rows.length===0&&<div className="empty">ยังไม่มีรายการในคิว</div>}</div></div>}
