"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {CalendarClock,Check,Copy,ExternalLink,Loader2,Plus,Trash2,X} from "lucide-react";
import {createClient} from "@/lib/supabase/client";
type G={id:string;name:string;facebook_url:string|null;active:boolean};type C={id:string;title:string;body:string;status:string};type Q={id:string;scheduled_at:string;status:string;error_message:string|null;groups:G|null;contents:C|null};
export default function QueueManager(){const supabase=useMemo(()=>createClient(),[]);const [groups,setGroups]=useState<G[]>([]),[contents,setContents]=useState<C[]>([]),[items,setItems]=useState<Q[]>([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[groupId,setGroupId]=useState(""),[contentId,setContentId]=useState(""),[scheduled,setScheduled]=useState("");
 const load=async()=>{setLoading(true);const [g,c,q]=await Promise.all([supabase.from("groups").select("id,name,facebook_url,active").eq("active",true).order("name"),supabase.from("contents").select("id,title,body,status").neq("status","archived").order("created_at",{ascending:false}),supabase.from("daily_queue").select("id,scheduled_at,status,error_message,groups(id,name,facebook_url,active),contents(id,title,body,status)").order("scheduled_at",{ascending:true})]);setGroups((g.data??[]) as G[]);setContents((c.data??[]) as C[]);setItems((q.data??[]) as unknown as Q[]);setLoading(false)};useEffect(()=>{void load()},[]);
 const add=async(e:FormEvent)=>{e.preventDefault();const r=await supabase.from("daily_queue").insert({group_id:groupId,content_id:contentId,scheduled_at:new Date(scheduled).toISOString()});if(r.error)alert(r.error.message);else{setOpen(false);setGroupId("");setContentId("");setScheduled("");await load()}};
 const mark=async(x:Q,status:string)=>{await supabase.from("daily_queue").update({status,updated_at:new Date().toISOString()}).eq("id",x.id);if(status==="posted"||status==="failed"){await supabase.from("posting_history").insert({queue_id:x.id,group_id:x.groups?.id,content_id:x.contents?.id,result:status,posted_at:new Date().toISOString()})}await load()};
 const grouped=items.reduce<Record<string,Q[]>>((a,x)=>{const k=new Date(x.scheduled_at).toLocaleDateString("th-TH",{weekday:"long",day:"numeric",month:"long",year:"numeric"});(a[k]??=[]).push(x);return a},{});
 return <div className="space-y-5"><div className="flex flex-col gap-3 rounded-2xl border border-white/10 bg-white/[.035] p-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-bold">วางแผนโพสต์</h2><p className="text-sm text-white/45">เลือกคอนเทนต์ กลุ่ม และเวลาที่ต้องการ</p></div><button onClick={()=>setOpen(true)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-black"><Plus size={18}/>เพิ่มคิวโพสต์</button></div>
 {loading?<div className="grid min-h-64 place-items-center"><Loader2 className="animate-spin"/></div>:items.length?<div className="space-y-6">{Object.entries(grouped).map(([date,rows])=><section key={date}><h3 className="mb-3 text-sm font-bold text-cyan-300">{date}</h3><div className="space-y-2">{rows.map(x=><div key={x.id} className="flex flex-col gap-3 rounded-2xl border border-white/10 bg-white/[.03] p-4 md:flex-row md:items-center"><div className="w-20 text-lg font-black">{new Date(x.scheduled_at).toLocaleTimeString("th-TH",{hour:"2-digit",minute:"2-digit"})}</div><div className="min-w-0 flex-1"><p className="truncate font-bold">{x.contents?.title||"คอนเทนต์ถูกลบ"}</p><p className="truncate text-sm text-white/45">{x.groups?.name||"กลุ่มถูกลบ"}</p></div><span className="rounded-full border border-white/10 px-3 py-1 text-xs text-white/55">{x.status}</span><div className="flex gap-1"><button title="คัดลอกข้อความ" onClick={()=>navigator.clipboard.writeText(x.contents?.body||"")} className="rounded-lg p-2 hover:bg-white/10"><Copy size={17}/></button>{x.groups?.facebook_url&&<a href={x.groups.facebook_url} target="_blank" className="rounded-lg p-2 hover:bg-white/10"><ExternalLink size={17}/></a>}<button title="โพสต์สำเร็จ" onClick={()=>mark(x,"posted")} className="rounded-lg p-2 text-emerald-300 hover:bg-emerald-400/10"><Check size={18}/></button><button onClick={async()=>{if(confirm("ลบคิวนี้ใช่หรือไม่?")){await supabase.from("daily_queue").delete().eq("id",x.id);await load()}}} className="rounded-lg p-2 text-red-300 hover:bg-red-400/10"><Trash2 size={17}/></button></div></div>)}</div></section>)}</div>:<div className="grid min-h-72 place-items-center rounded-2xl border border-dashed border-white/10 text-center"><div><CalendarClock className="mx-auto text-white/20" size={38}/><p className="mt-3 text-white/50">ยังไม่มีคิวโพสต์</p></div></div>}
 {open&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/75 p-4"><form onSubmit={add} className="w-full max-w-lg rounded-2xl border border-white/10 bg-[#101319] p-5"><div className="mb-5 flex justify-between"><div><h2 className="text-xl font-bold">เพิ่มคิวโพสต์</h2><p className="text-sm text-white/45">ระบบจะเก็บเป็นรายการรอให้คุณดำเนินการ</p></div><button type="button" onClick={()=>setOpen(false)}><X/></button></div><label className="mb-4 block"><span className="mb-1 block text-sm text-white/60">Facebook Group</span><select required className="form-input" value={groupId} onChange={e=>setGroupId(e.target.value)}><option value="">เลือกกลุ่ม</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><label className="mb-4 block"><span className="mb-1 block text-sm text-white/60">คอนเทนต์</span><select required className="form-input" value={contentId} onChange={e=>setContentId(e.target.value)}><option value="">เลือกคอนเทนต์</option>{contents.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label className="mb-5 block"><span className="mb-1 block text-sm text-white/60">วันและเวลา</span><input required type="datetime-local" className="form-input" value={scheduled} onChange={e=>setScheduled(e.target.value)}/></label><button className="w-full rounded-xl bg-white py-2.5 font-bold text-black">เพิ่มเข้าคิว</button></form></div>}
 </div>}
